src/Components/CardHistorico/index.js, src/Components/CardHistorico/styles.js, src/Components/CartCard/styles.js, src/Components/FeedCard/styles.js, src/pages/login/Login.js, src/pages/perfil/Perfil.js, src/pages/perfil/styles.js
=> CartCard, FeedCard, Login, CardHistorico

src/App.js, src/Components/CardHistorico/index.js, src/Components/CartCard/styles.js, src/pages/login/Login.js, src/pages/restaurante/index.js, src/pages/restaurante/styles.js
=> Restaurante

src/Components/FeedCard/index.js, src/Components/FeedCard/styles.js, src/pages/home/Home.css, src/pages/home/Home.js
=> Continuando as abas

src/Components/CartCard/index.js, src/Components/Header/styles.js, src/pages/cart/Carrinho.css, src/pages/cart/Carrinho.js, src/pages/home/Home.js
=> Fazendo o carrinho

src/Components/Button/index.js, src/Components/Button/styles.js
Botão implementado e testado. Sintam-se à vontade caso queiram estilizar.
=> Botão implementado

src/Components/Button/index.js, src/Components/Button/styles.js
Botão funcionando corretamente como esperado.
=> Funcionalidade ativado/desativado do botão implementada

src/Components/CartCard/index.js, src/Components/CartCard/styles.js, src/Components/FeedCard/index.js, src/Components/FeedCard/styles.js, src/pages/cart/Carrinho.css, src/pages/cart/Carrinho.js, src/pages/home/Home.css, src/pages/home/Home.js
=> Branch gislaine2

src/pages/login/Login.js, src/pages/login/styles.js
Botão na página de Login corrigido.
=> Correção do botão na página de login

src/App.js, src/pages/editarCadastro/EditarCadastro.css, src/pages/editarCadastro/EditarCadastro.js, src/pages/editarCadastro/styles.js, src/pages/editarEndereco/EditarEndereco.css, src/pages/editarEndereco/EditarEndereco.js, src/pages/editarEndereco/styles.js, src/pages/perfil/Perfil.js
Faltando implementar a comunicação com a API e trocar a cor da borda do elemento TextField do Material-Ui.
=> Páginas de edição de cadastro e de endereço adicionadas.

src/App.js, src/Components/CartCard/index.js, src/Components/FeedCard/index.js, src/functions/integracao.js, src/pages/home/Home.js, src/pages/restaurante/index.js
=> mapeamento da api

src/Components/Button/index.js, src/pages/cart/Carrinho.js, src/pages/endereco/index.js, src/pages/home/Home.js, src/pages/login/Login.js, src/pages/perfil/Perfil.js, src/pages/restaurante/index.js
=> autenticação e autorização das páginas

src/App.js, src/Components/CartCard/index.js, src/functions/CardReducer.js, src/functions/CartContext.js, src/pages/cart/Carrinho.js
Cria o Contexto para o carrinho e já deixa à espera o de produtos e restaurantes
=> Context para o carrinho

src/App.js, src/functions/CardReducer.js
=> iniciando o contexto de restaurantes

src/functions/index.js, src/functions/integracao.js, src/pages/cart/Carrinho.js, src/pages/editarEndereco/EditarEndereco.js, src/pages/endereco/index.js, src/pages/home/Home.js, src/pages/perfil/Perfil.js, src/pages/registro/Registro.js, src/pages/restaurante/index.js
=> Integração com a API na página Home, melhorias na utilização do token

src/pages/cart/Carrinho.js
=> tentando o carrinho

src/App.js, src/Components/CartCard/index.js, src/Components/CartCard/styles.js, src/functions/CardContext.js, src/functions/CardReducer.js, src/functions/CartContext.js, src/functions/integracao.js, src/pages/cart/Carrinho.js, src/pages/home/Home.js, src/pages/perfil/Perfil.js, src/pages/perfil/styles.js, src/pages/restaurante/index.js, src/pages/restaurante/styles.js
Reducer ainda não terminado, olhar o Trello
=> Contexto e Reducer Carrinho e Home

src/App.js, src/img/procurar.svg, src/pages/busca/Busca.js, src/pages/home/Home.css, src/pages/home/Home.js, src/pages/restaurante/index.js, src/pages/restaurante/styles.js
Adiciona chave quantidade ao array de produtos de um restaurante
adiciona a quantidade selecionada 
Remove a quantidade
Não atualiza a tela depois de remover
Tem que passar para o carrinho
=> Função para selecionar a quantidade de produtos

src/pages/editarCadastro/EditarCadastro.js, src/pages/editarEndereco/EditarEndereco.js
Páginas implementadas, faltando apenas retirar a cor das bordas quando começamos a digitar
=> Páginas de edição implementadas

src/App.js, src/Components/Alert/Alert.js, src/functions/CardReducer.js, src/functions/integracao.js, src/pages/home/Home.js
O pedido em andamento aparece na tela mas não atualiza quando termina
=> Tentando atualizar o pedido em andamento

src/pages/cart/Carrinho.js, src/pages/home/Home.js, src/pages/restaurante/index.js
- Com relação às páginas de restaurante, está funcionando a renderização categorizada dos produtos.
- Quase nada.
=> [Semana13-FutureEatsB] Adicionando alterações nas páginas de restaurante
